### ISSUE TITLE
the child of the prefab not displayed on the graph

### ISSUE THREAD

**Issue by Kaorixsol** [Begounet/unity-dependency-graph-viewer#1]
Hello, respected developer.
Is the resource reference of the child of the prefab not displayed on the graph?I have a prefab whose his children refer to a texture and a material.

![1](https://user-images.githubusercontent.com/20392465/64396588-b4480e80-d090-11e9-8841-82ef67531955.png)

![2](https://user-images.githubusercontent.com/20392465/64396624-ca55cf00-d090-11e9-86c1-1e6b85f8c200.png)

Dependency Viewer is only the GameObject Prefab

Is it because I am not using it properly?

**Comment by Begounet** [comment]
Hello, also respected developer!

Oh! I didn't think about searching in prefab children!
I kind of gave up this plugin for now but I will work on it this weekend then ^^

I also wanted to add some cache system so you manually build it once and the next searches will be faster.

I will put priority on prefab dependency so you can use it quickly if you need it.

Please, feel free to tell me if there is another kind of dependency that should be found but it is not in the current state of the plugin.

**Comment by Begounet** [comment]
Hello!

It should be ok now.

![UDGV - BrowsePrefabChildren](https://user-images.githubusercontent.com/6328801/64477378-2e64ba00-d19b-11e9-8230-a15170623902.JPG)


References will also be found, and a new line will appear to display the prefab and you can have the name of the GameObject that contains the reference from the tooltip.

![image](https://user-images.githubusercontent.com/6328801/64477960-d2e9fa80-d1a1-11e9-9c6b-1f7a9aaa62ca.png)


Have a nice day!
